/*
 *    
 *    Copyright (C) 2006, Network Resonance, Inc.
 *    All Rights Reserved
 *    
 *    Redistribution and use in source and binary forms, with or without
 *    modification, are permitted provided that the following conditions
 *    are met:
 *    
 *    1. Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *    2. Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *    3. Neither the name of Network Resonance, Inc. nor the name of any
 *       contributors to this software may be used to endorse or promote 
 *       products derived from this software without specific prior written
 *       permission.
 *    
 *    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS''
 *    AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 *    IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 *    ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE 
 *    LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 *    CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 *    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 *    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 *    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *    POSSIBILITY OF SUCH DAMAGE.
 *    
 */
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "regrpc.h"

bool_t
xdr_nr_regd_registry(XDR *xdrs, nr_regd_registry *objp)
{

	if (!xdr_string(xdrs, objp, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_regd_data(XDR *xdrs, nr_regd_data *objp)
{

	if (!xdr_bytes(xdrs, (char **)&objp->nr_regd_data_val, (u_int *)&objp->nr_regd_data_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_regd_string(XDR *xdrs, nr_regd_string *objp)
{

	if (!xdr_string(xdrs, objp, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_regd_result_char(XDR *xdrs, nr_regd_result_char *objp)
{

	if (!xdr_int(xdrs, &objp->retval))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->out))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_regd_result_UCHAR(XDR *xdrs, nr_regd_result_UCHAR *objp)
{

	if (!xdr_int(xdrs, &objp->retval))
		return (FALSE);
	if (!xdr_u_char(xdrs, &objp->out))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_regd_result_INT2(XDR *xdrs, nr_regd_result_INT2 *objp)
{

	if (!xdr_int(xdrs, &objp->retval))
		return (FALSE);
	if (!xdr_int16_t(xdrs, &objp->out))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_regd_result_UINT2(XDR *xdrs, nr_regd_result_UINT2 *objp)
{

	if (!xdr_int(xdrs, &objp->retval))
		return (FALSE);
	if (!xdr_u_int16_t(xdrs, &objp->out))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_regd_result_INT4(XDR *xdrs, nr_regd_result_INT4 *objp)
{

	if (!xdr_int(xdrs, &objp->retval))
		return (FALSE);
	if (!xdr_int32_t(xdrs, &objp->out))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_regd_result_UINT4(XDR *xdrs, nr_regd_result_UINT4 *objp)
{

	if (!xdr_int(xdrs, &objp->retval))
		return (FALSE);
	if (!xdr_u_int32_t(xdrs, &objp->out))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_regd_result_INT8(XDR *xdrs, nr_regd_result_INT8 *objp)
{

	if (!xdr_int(xdrs, &objp->retval))
		return (FALSE);
	if (!xdr_int64_t(xdrs, &objp->out))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_regd_result_UINT8(XDR *xdrs, nr_regd_result_UINT8 *objp)
{

	if (!xdr_int(xdrs, &objp->retval))
		return (FALSE);
	if (!xdr_u_int64_t(xdrs, &objp->out))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_regd_result_double(XDR *xdrs, nr_regd_result_double *objp)
{

	if (!xdr_int(xdrs, &objp->retval))
		return (FALSE);
	if (!xdr_double(xdrs, &objp->out))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_regd_result_bytes(XDR *xdrs, nr_regd_result_bytes *objp)
{

	if (!xdr_int(xdrs, &objp->retval))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->out.out_val, (u_int *)&objp->out.out_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_regd_result_string(XDR *xdrs, nr_regd_result_string *objp)
{

	if (!xdr_int(xdrs, &objp->retval))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->out, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_regd_result_strings(XDR *xdrs, nr_regd_result_strings *objp)
{

	if (!xdr_int(xdrs, &objp->retval))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->out.out_val, (u_int *)&objp->out.out_len, ~0, sizeof(nr_regd_string), (xdrproc_t)xdr_nr_regd_string))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_reg_set_char_1_argument(XDR *xdrs, nr_reg_set_char_1_argument *objp)
{
	if (!xdr_nr_regd_registry(xdrs, &objp->name))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_reg_set_uchar_1_argument(XDR *xdrs, nr_reg_set_uchar_1_argument *objp)
{
	if (!xdr_nr_regd_registry(xdrs, &objp->name))
		return (FALSE);
	if (!xdr_u_char(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_reg_set_int2_1_argument(XDR *xdrs, nr_reg_set_int2_1_argument *objp)
{
	if (!xdr_nr_regd_registry(xdrs, &objp->name))
		return (FALSE);
	if (!xdr_int16_t(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_reg_set_uint2_1_argument(XDR *xdrs, nr_reg_set_uint2_1_argument *objp)
{
	if (!xdr_nr_regd_registry(xdrs, &objp->name))
		return (FALSE);
	if (!xdr_u_int16_t(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_reg_set_int4_1_argument(XDR *xdrs, nr_reg_set_int4_1_argument *objp)
{
	if (!xdr_nr_regd_registry(xdrs, &objp->name))
		return (FALSE);
	if (!xdr_int32_t(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_reg_set_uint4_1_argument(XDR *xdrs, nr_reg_set_uint4_1_argument *objp)
{
	if (!xdr_nr_regd_registry(xdrs, &objp->name))
		return (FALSE);
	if (!xdr_u_int32_t(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_reg_set_int8_1_argument(XDR *xdrs, nr_reg_set_int8_1_argument *objp)
{
	if (!xdr_nr_regd_registry(xdrs, &objp->name))
		return (FALSE);
	if (!xdr_int64_t(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_reg_set_uint8_1_argument(XDR *xdrs, nr_reg_set_uint8_1_argument *objp)
{
	if (!xdr_nr_regd_registry(xdrs, &objp->name))
		return (FALSE);
	if (!xdr_u_int64_t(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_reg_set_double_1_argument(XDR *xdrs, nr_reg_set_double_1_argument *objp)
{
	if (!xdr_nr_regd_registry(xdrs, &objp->name))
		return (FALSE);
	if (!xdr_double(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_reg_set_bytes_1_argument(XDR *xdrs, nr_reg_set_bytes_1_argument *objp)
{
	if (!xdr_nr_regd_registry(xdrs, &objp->name))
		return (FALSE);
	if (!xdr_nr_regd_data(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nr_reg_set_string_1_argument(XDR *xdrs, nr_reg_set_string_1_argument *objp)
{
	if (!xdr_nr_regd_registry(xdrs, &objp->name))
		return (FALSE);
	if (!xdr_nr_regd_string(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}
